name: past_question_paper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2+1 # This version number should be incremented for each change you make.

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.16.1
  fancy_bottom_navigation: ^0.3.3
  firebase_auth: ^4.19.1
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  svg_flutter: ^0.0.1
  tuple: ^2.0.2
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  another_flushbar: ^1.12.30
  google_nav_bar: ^5.0.7
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/past_question_paper.jpg" #launcher icon image path

flutter_native_splash:
  color : "#f7f6f1"
  color_dark : "#272727"
  image : assets/images/splash_screen.png #splash screen image path
  image_dark: assets/images/past_question_paper.jpg
  android: true

  android_12 :
  icon_background_color : "#f7f6f1"
  icon_background_color_dark: "#272727"
  

flutter:
  uses-material-design: true
  assets :
    - assets/images/
    - assets/images/past_question_paper.jpg
    - assets/subjects/
    - assets/icons/
    - assets/animations/
