// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfE8K3J2oKsaDx9aYzm-ANPB3AVKUiuk',
    appId: '1:671420766858:web:ba1552ba6c553788cb6b73',
    messagingSenderId: '671420766858',
    projectId: 'kinetixes-ecfe8',
    authDomain: 'kinetixes-ecfe8.firebaseapp.com',
    storageBucket: 'kinetixes-ecfe8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAccg7qaqgrQ5RaoLJwl5Km5WDCVVEz9R0',
    appId: '1:671420766858:android:94f955608237c6a5cb6b73',
    messagingSenderId: '671420766858',
    projectId: 'kinetixes-ecfe8',
    storageBucket: 'kinetixes-ecfe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF3ijWGZKaCJMrFGszrhKMTpaESAUR9d0',
    appId: '1:671420766858:ios:aa98d639af035f23cb6b73',
    messagingSenderId: '671420766858',
    projectId: 'kinetixes-ecfe8',
    storageBucket: 'kinetixes-ecfe8.appspot.com',
    iosBundleId: 'com.example.matricApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF3ijWGZKaCJMrFGszrhKMTpaESAUR9d0',
    appId: '1:671420766858:ios:f4ef7a0be8dfc0f2cb6b73',
    messagingSenderId: '671420766858',
    projectId: 'kinetixes-ecfe8',
    storageBucket: 'kinetixes-ecfe8.appspot.com',
    iosBundleId: 'com.example.matricApp.RunnerTests',
  );
}
